backend = "glx";
glx-no-stencil = true;
vsync = true;
unredir-if-possible = true;
 
# Shadow
shadow = true; # Enabled client-side shadows on windows.
shadow-radius = 20; # The blur radius for shadows. (default 12)
shadow-offset-x = -15; # The left offset for shadows. (default -15)
shadow-offset-y = -15; # The top offset for shadows. (default -15)
shadow-color = "#103586"
shadow-exclude = [
    "n:e:Notification",
    "n:e:Docky",
    "g:e:Synapse",
    "g:e:Conky",
    "n:w:*Firefox*",
    "n:w:*Chromium*",
    "n:w:*dockbarx*",
    "class_g ?= 'Cairo-dock'",
    "class_g ?= 'Xfce4-notifyd'",
    "class_g ?= 'Xfce4-power-manager'",
    "class_g ?= 'Notify-osd'",
    "class_g = 'firefox' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
    "class_g = 'Dunst'",
    "QTILE_INTERNAL:32c = 1",
];
 
# Opacity
# detect-client-opacity = true;
# menu-opacity = 0.9;
frame-opacity = 0.85;
active-opacity = 0.85;
inactive-opacity = 0.55;
opacity-rule = [
    "100:name*?='vlc'",
    "100:name*?= 'Picture-in-Picture'",
    "100:fullscreen"
]
 
# Window type settings
wintypes =
{
    dock = { shadow = false; };
    dnd = { shadow = false; };
    tooltip = { shadow = false; };
};


# Blur
blur-method = "dual_kawase";
blur-strength = 4;

blur-background-exclude = [
]


# Corners

corner-radius = 17.0;
round-borders = 1;
rounded-corners-exclude = [
    "class_g ?= 'Tint2'",
    "QTILE_INTERNAL:32c = 1",
    "class_g = 'Dunst'",
    "class_g = 'i3bar'"
]


# Animations:

animations = ({
    triggers = [ "close", "hide" ];
    preset = "disappear";
    duration = 0.3;
},
{
    triggers = [ "open" ];
    preset = "appear";
    duration = 0.3;
},
{
    triggers = [ "geometry" ];
    preset = "geometry-change";
    exclude = [
        "class_g = 'Pcmanfm'",
        "name ?= Picture-in-Picture",
    ]
})

